- lib/util/index.js
moving select functions to mixpanel-common since they're being used in multiple places in collect-everything
context: https://github.com/mixpanel/analytics/pull/7098/files/80c093c42993f5986197ae89cd9b53f3531fb92a#r66316980
> add utils from analytics to mixpanel-common

- lib/report/constants.js
> add constant $all_events

- lib/report/mp-app.js
> configurable key for report localstorage

- lib/report/index.js
- lib/report/tracking-setup.js
- package.json
> tracking initialization utils

- report
- util
so you can import from `'mixpanel-common/util'` and `'mixpanel-common/report'`.
if you need the original ES2015 src you can always specify `'mixpanel-common/lib/util'`
> add util/ and report/ symlinks

- lib/util/index.js
- test/util.js
Adds some array manipulation utilities
> Immutable splice

- examples/index.html
- lib/components/buttons/button.styl
https://mixpanel.atlassian.net/browse/CA-684
> CA-684: Add active button styles

- lib/components/buttons/button.styl
https://mixpanel.atlassian.net/browse/CA-718
> CA-718: Update active button styles

- lib/util/index.js
- test/util.js
implemented without reduce and other trickery, to keep it lightweight and fast enough
> super important sum() util

- examples/index.html
- lib/components/modals/modal.jade
- lib/components/modals/modal.js
- lib/components/modals/modal.styl
don't modify the dom directly; use state to handle visibility
> fix modal opening/closing

- examples/panel-example/compiled/index.js
- examples/style-guide/compiled/index.js
- lib/components/buttons/button.styl
- lib/components/modals/modal.styl
- lib/components/toggles/index.styl
- lib/components/tooltips/tooltip.styl
- package.json
changed styles for: buttons, toggle bars, tooltip, dropshadow on modal, and added comments for necessary markup changes.
> Updates to common styles

- examples/style-guide/index.jade
- lib/components/drop-menu/index.js
mp-drop-menu now closes when you hit escape
> added esc listener to close menu

- lib/widgets/bookmarks-widget/index.jade
- lib/widgets/bookmarks-widget/index.js
- lib/widgets/tag-selector/index.styl
- take away delete button in each bookmark list item
- take away main create button
> Add permissions restrictions to bookmarks widget

- examples/style-guide/index.jade
- examples/style-guide/index.styl
- lib/widgets/index.js
- lib/widgets/tutorial-tooltip/index.jade
- lib/widgets/tutorial-tooltip/index.js
- lib/widgets/tutorial-tooltip/index.styl
Used in https://github.com/mixpanel-platform/irb/pull/176
Mocks here https://app.zeplin.io/project.html#pid=5810e4117899d27c64470e4d&sid=586d4590ce6f17fe76c9d026
https://projects.invisionapp.com/d/main#/console/9497805/211293609/preview
> Tutorial tooltip

- examples/style-guide/index.jade
- examples/style-guide/index.js
cleaned up the bookmark opens and added headers for new bookmark examples
> cleaned up styleguide example for bookmarks

- lib/widgets/upsell-modal/index.styl
> box shadow re: Mason

- lib/components/tag/index.styl
- lib/widgets/bookmarks-widget/index.jade
- lib/widgets/tag-selector/index.styl
- test/widgets/tag-selector.js
Fixing a couple issues that arose with cross-browser testing
> Play nice with Firefox & Safari

- lib/util/date.js
- package.json
- test/util/date.js
Move date utils from Insights here and add unit tests for them
corresponding Insights branch: https://github.com/mixpanel-platform/insights/pull/323
> Date utils

- lib/widgets/add-to-dash/index.styl
- test/components/tag.js
- test/widgets/tag-selector.js
> Fix tag tests

- examples/style-guide-new/compiled/index.js
- examples/style-guide/compiled/index.js
- lib/util/date.js
- package.json
- test/util/date.js
release branch for https://github.com/mixpanel/mixpanel-common/pull/200 (to allow CI to run)
> Allow offsets release

- examples/style-guide/index.jade
- lib/components/button/index.jade
- lib/components/button/index.styl
> Add small button

- examples/style-guide/index.jade
- examples/style-guide/index.js
- lib/widgets/tutorial-tooltip/index.jade
- lib/widgets/tutorial-tooltip/index.js
- lib/widgets/tutorial-tooltip/index.styl
> add next button

- examples/style-guide-new/compiled/index.js
- examples/style-guide/compiled/index.js
common examples NEW.. hopefully updated.
> published files

- examples/style-guide-new/components/nav-bar/index.jade
- examples/style-guide-new/components/widgets/index.jade
- examples/style-guide-new/components/widgets/index.js
- examples/style-guide-new/components/widgets/index.styl
- examples/style-guide-new/search-terms.json
- examples/style-guide/index.js
Basically copied over from the old style guide.
> Add mp-items-menu to new style guide

- readme.md
(and remove unmaintained release log)
> Add Saucelabs command to readme

- examples/style-guide-new/components/components/index.jade
- examples/style-guide-new/components/widgets/index.jade
- examples/style-guide-new/components/widgets/index.styl
- examples/style-guide-new/index.styl
> Updates to styling for styleguide
